name: Create an auto comment on issue

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: structure of issue
        run: echo '${{ toJson(github.event) }}' | jq
        shell: bash
      - name: create a comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Comment with github action! Created By Saumya :)
          reactions: '+1'

  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: create comment with api
        run: |
          gh api -X POST \
            https://api.github.com/repos/${ORG}/${REPO}/issues/${ISSUE_NUMBER}/comments \
            -f body='comment with github api'
        env:
          ORG: ${{ github.event.organization.login }}
          REPO: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
